apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v3n9shi60-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v3n9shi60-java-springboot-gitops